<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE library [
    <!ELEMENT library (dvd)*>
    <!ELEMENT dvd (genre|format|title)*>
    <!ATTLIST dvd id CDATA #IMPLIED >

    <!ELEMENT title (#PCDATA)>
    <!ELEMENT format (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
<!--    
    <!ENTITY classic "CLASSIC">
    <!ENTITY class SYSTEM "file:///users/bowsnickiklewe/SecretPw.txt">
    -->    
    <!ENTITY class SYSTEM "file:///users//bowsnickiklewe/ger/classic.txt">
]>
<!-- This XML document describes a dvd library Â  -->
<library>
    <dvd id="1">
        <title>Breakfast at Tiffany's</title>
        <format>Movie</format>
        <genre>&class;</genre>
    </dvd>
    <dvd id="2">
        <title>Contact</title>
        <format>Movie</format>
        <genre>Science fiction</genre>
    </dvd>
    <dvd id="3">
        <title>Little Britain</title>
        <format>TV Series</format> 
        <genre>Comedy</genre>
    </dvd>
</library>